---
type: object
properties:
  logging:
    type: object
    properties:
      modlog:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      serverlog:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      userlog:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
  staff:
    type: object
    properties:
      adminrole:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      modrole:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      botrole:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      staffchannel:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      rulesurl:
        type:
          - string
          - "null"
      appealurl:
        type:
          - string
          - "null"
  mute:
    type: object
    properties:
      muterole:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      mutecategory:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      notificationchannel:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      mutechannels:
        type:
          - array
          - "null"
        items:
          type:
            - integer
            - string
          minimum: 100000000000000000
      mutetopic:
        type:
          - string
          - "null"
  reaction:
    type: object
    properties:
      autoreadableenable:
        type:
          - boolean
          - "null"
  overrides:
    type:
      - array
      - "null"
    items:
      type: object
      properties:
        command:
          type: string
        roles:
          type: array
          items:
            type:
              - integer
              - string
            minimum: 100000000000000000
        restrict:
          type: boolean
  drive:
    type: object
    properties:
      folder:
        type: string
  metadata:
    type: object
    properties:
      version:
        const: 10
